name: pre-release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  validate:
    name: Validate CHANGELOG
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'chore(release):') }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Validate structure
        run: npx tsx scripts/release/validate-changelog.ts

  pre-release:
    name: Apply version and tag
    needs: validate
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'chore(release):') }}
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - id: apply
        name: Compute and apply next version
        uses: actions/github-script@v7
        with:
          script: |
            require('ts-node/register/transpile-only');
            await require('./scripts/release/apply-release.ts').default(core);

      - run: bash scripts/git-user-config.sh
      - name: Commit version bump and changelog update
        if: steps.apply.outputs.skip != 'true'
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
      
          echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
          
          git add package.json package-lock.json CHANGELOG.md
          if ! git diff --cached --quiet; then
            git commit -m "chore(release): v${{ steps.apply.outputs.version }}"
            git tag v${{ steps.apply.outputs.version }}
            GIT_SSH_COMMAND="ssh -i ~/.ssh/deploy_key -o IdentitiesOnly=yes" git push origin
            GIT_SSH_COMMAND="ssh -i ~/.ssh/deploy_key -o IdentitiesOnly=yes" git push origin --tags
          fi
